title: Explore CS Research (ECSR)
description: Exposing undergraduate students to computer science research at the University of Michigan
baseurl: "/ecsr-website"
url: ""

markdown: kramdown
permalink: pretty
