title: Explore CS Research (ECSR)
description: Exposing undergraduate students to computer science research at the University of Michigan

url: "https://ecsr.engin.umich.edu"
baseurl: ""

markdown: kramdown
permalink: pretty
